-- ============================================================
-- Client DB2 queries used by WFM Control-M
-- Placeholders: {days}, {stalePendingDbMins}, {maxBatchDetailRows},
--   {payrollLookbackDays}, {punchLookbackDays}, {jobType}, {planType}, {schema}, {table}
-- ============================================================

-- ---------- DB2 Direct (JDBC / DB2Connector.js) ----------

-- test connection
SELECT CURRENT TIMESTAMP AS TS FROM SYSIBM.SYSDUMMY1;

-- tables (connector action; not wired to an API route today)
SELECT TABSCHEMA, TABNAME, CARD AS ROW_COUNT
FROM SYSCAT.TABLES
WHERE TYPE = 'T'
  AND (TABNAME LIKE '%JOB%' OR TABNAME LIKE '%BATCH%' OR TABNAME LIKE '%SCHEDULE%'
    OR TABNAME LIKE '%TASK%' OR TABNAME LIKE '%WFM%' OR TABNAME LIKE '%CRON%')
ORDER BY TABSCHEMA, TABNAME
FETCH FIRST 100 ROWS ONLY;

-- batch status grouped
SELECT JOB_TYPE, PLAN_TYPE, COUNT(*) AS CNT,
  SUM(CASE WHEN STATUS='C' THEN 1 ELSE 0 END) AS COMPLETED,
  SUM(CASE WHEN STATUS IN ('E','F') THEN 1 ELSE 0 END) AS FAILED,
  SUM(CASE WHEN STATUS='A' THEN 1 ELSE 0 END) AS ACTIVE,
  SUM(CASE WHEN STATUS='N' THEN 1 ELSE 0 END) AS PENDING,
  SUM(CASE WHEN STATUS='N' AND TIME_SUBMITTED IS NOT NULL
    AND TIME_SUBMITTED < CURRENT TIMESTAMP - {stalePendingDbMins} MINUTES THEN 1 ELSE 0 END) AS STALE_PENDING,
  MAX(TIME_SUBMITTED) AS LATEST_RUN,
  MAX(DESCRIPTION) AS DESCR
FROM RWSUSER.BATCH_STATUS
WHERE TIME_SUBMITTED >= CURRENT TIMESTAMP - {days} DAYS
GROUP BY JOB_TYPE, PLAN_TYPE
ORDER BY CNT DESC;

-- batch status details
SELECT bs.BATCH_STATUS_ID, bs.JOB_TYPE, bs.STATUS, bs.START_DATE_SKEY,
  bs.TIME_SUBMITTED, bs.TIME_COMPLETED, bs.DESCRIPTION, bs.TOTAL_JOBS, bs.PENDING_JOBS, bs.UNIT_SKEY,
  (SELECT COUNT(1) FROM RWSUSER.RFX_QUEUE_JOB q WHERE q.BATCH_STATUS_ID = bs.BATCH_STATUS_ID AND q.JOB_ESTATUS='S') AS SUCCESS_COUNT,
  (SELECT COUNT(1) FROM RWSUSER.RFX_QUEUE_JOB q WHERE q.BATCH_STATUS_ID = bs.BATCH_STATUS_ID AND q.JOB_ESTATUS='F') AS FAIL_COUNT,
  (SELECT COUNT(1) FROM RWSUSER.RFX_QUEUE_JOB q WHERE q.BATCH_STATUS_ID = bs.BATCH_STATUS_ID AND q.JOB_ESTATUS NOT IN ('S','F')) AS OTHER_COUNT
FROM RWSUSER.BATCH_STATUS bs
WHERE bs.JOB_TYPE = '{jobType}'
  AND ({planTypeFilter})
  AND bs.TIME_SUBMITTED >= CURRENT TIMESTAMP - {days} DAYS
ORDER BY bs.TIME_SUBMITTED DESC
FETCH FIRST {maxBatchDetailRows} ROWS ONLY;

-- queue jobs (running)
SELECT q.JOB_TYPE, COALESCE(EXEC_CRON, CHAR(QUEUE_SLEEP)) JOB_INTERVAL, PARAM_2, LAST_JOB_TIME, JOBS_PENDING
FROM RWSUSER.RFX_QUEUE q
LEFT JOIN RWSUSER.STD_QUEUE_JOB s ON s.QUEUE_ID = q.QUEUE_ID
WHERE q.QUEUE_STATUS = 'R'
ORDER BY JOBS_PENDING DESC, LAST_JOB_TIME;

-- payroll status
SELECT * FROM RWSUSER.TA_UNIT_PAY_STATUS
WHERE to_date(WEEK_END_DATE,'yyyyMMdd') >= CURRENT DATE - {payrollLookbackDays} DAYS
  AND to_date(WEEK_END_DATE,'yyyyMMdd') <= CURRENT DATE
ORDER BY WEEK_START_DATE DESC, UNIT_ID;

-- payroll RTA integration sync
SELECT FEATURE_VALUE FROM RWSUSER.PRODUCT_FEATURE
WHERE feature_id LIKE 'RTA_INTEGRATION'
FETCH FIRST 1 ROW ONLY;

-- unprocessed punches
SELECT COUNT(1) AS PUNCH_COUNT, MIN(LAST_UPDATE_TIME) AS LAST_UPDATE_TIME, CURRENT TIMESTAMP AS DB_CURRENT_TS
FROM RWSUSER.TA_UNPROC_PUNCH
WHERE PROCESS_FLAG = 'N'
  AND INTEGER(PUNCH_DATE) >= INTEGER(VARCHAR_FORMAT(CURRENT DATE - {punchLookbackDays} DAYS, 'yyyyMMdd'));

-- ---------- DB Monitor (SSH + db2 CLI) ----------

-- table list
SELECT TABNAME, CARD AS ROW_COUNT, STATS_TIME
FROM SYSCAT.TABLES
WHERE TABSCHEMA = '{schema}' AND TYPE = 'T'
ORDER BY TABNAME;

-- discover WFM-related tables
SELECT TABNAME FROM SYSCAT.TABLES
WHERE TABSCHEMA = '{schema}' AND TYPE = 'T'
  AND (TABNAME LIKE '%JOB%' OR TABNAME LIKE '%BATCH%' OR TABNAME LIKE '%SCHEDULE%'
    OR TABNAME LIKE '%TASK%' OR TABNAME LIKE '%EXEC%')
ORDER BY TABNAME;

-- job status: BATCH_JOB pattern
SELECT JOB_NAME, STATUS, LAST_RUN_TIME, NEXT_RUN_TIME, EXIT_CODE
FROM {schema}.{table}
FETCH FIRST 100 ROWS ONLY;

-- job status: JOB_EXECUTION / BATCH_JOB_EXEC pattern
SELECT JOB_NAME, STATUS, START_TIME, EXIT_CODE, DURATION
FROM {schema}.{table}
ORDER BY START_TIME DESC
FETCH FIRST 50 ROWS ONLY;

-- job status: JOB_SCHEDULE / SCHEDULE pattern
SELECT JOB_NAME, STATUS, SCHEDULED_AT, NEXT_RUN_TIME
FROM {schema}.{table}
FETCH FIRST 100 ROWS ONLY;

-- ad-hoc: user-supplied SELECT only (POST /api/db-monitor/:id/query)
