-- ============================================================
-- Client DB2 queries used by WFM Control-M
-- Placeholders: {days}, {stalePendingDbMins}, {maxBatchDetailRows},
--   {weekEndDate}, {punchLookbackDays}, {jobType}, {planType}, {schema}, {table}
-- ============================================================

-- ---------- DB2 Direct (JDBC / DB2Connector.js) ----------

-- test connection
SELECT CURRENT TIMESTAMP AS TS FROM SYSIBM.SYSDUMMY1;

-- tables (connector action; not wired to an API route today)
SELECT TABSCHEMA, TABNAME, CARD AS ROW_COUNT
FROM SYSCAT.TABLES
WHERE TYPE = 'T'
  AND (TABNAME LIKE '%JOB%' OR TABNAME LIKE '%BATCH%' OR TABNAME LIKE '%SCHEDULE%'
    OR TABNAME LIKE '%TASK%' OR TABNAME LIKE '%WFM%' OR TABNAME LIKE '%CRON%')
ORDER BY TABSCHEMA, TABNAME
FETCH FIRST 100 ROWS ONLY;

-- batch status grouped
SELECT JOB_TYPE, PLAN_TYPE, COUNT(*) AS CNT,
  SUM(CASE WHEN STATUS='C' THEN 1 ELSE 0 END) AS COMPLETED,
  SUM(CASE WHEN STATUS IN ('E','F') THEN 1 ELSE 0 END) AS FAILED,
  SUM(CASE WHEN STATUS='A' THEN 1 ELSE 0 END) AS ACTIVE,
  SUM(CASE WHEN STATUS IN ('N','I') THEN 1 ELSE 0 END) AS PENDING,
  SUM(CASE WHEN STATUS IN ('N','I') AND TIME_SUBMITTED IS NOT NULL
    AND TIME_SUBMITTED < CURRENT TIMESTAMP - {stalePendingDbMins} MINUTES THEN 1 ELSE 0 END) AS STALE_PENDING,
  MAX(TIME_SUBMITTED) AS LATEST_RUN,
  MAX(DESCRIPTION) AS DESCR
FROM RWSUSER.BATCH_STATUS
WHERE TIME_SUBMITTED >= CURRENT TIMESTAMP - {days} DAYS
GROUP BY JOB_TYPE, PLAN_TYPE
ORDER BY CNT DESC;

-- batch status details
SELECT bs.BATCH_STATUS_ID, bs.JOB_TYPE, bs.STATUS, bs.START_DATE_SKEY,
  bs.TIME_SUBMITTED, bs.TIME_COMPLETED, bs.DESCRIPTION, bs.TOTAL_JOBS, bs.PENDING_JOBS, bs.UNIT_SKEY,
  CASE WHEN bs.STATUS IN ('N','I') THEN 1 ELSE 0 END AS IS_PENDING,
  CASE WHEN bs.STATUS IN ('N','I') AND bs.TIME_SUBMITTED IS NOT NULL
    AND bs.TIME_SUBMITTED < CURRENT TIMESTAMP - {stalePendingDbMins} MINUTES THEN 1 ELSE 0 END AS IS_STALE,
  TIMESTAMPDIFF(4, CHAR(CURRENT TIMESTAMP - bs.TIME_SUBMITTED)) AS AGE_MINS,
  (SELECT COUNT(1) FROM RWSUSER.RFX_QUEUE_JOB q WHERE q.BATCH_STATUS_ID = bs.BATCH_STATUS_ID AND q.JOB_ESTATUS='S') AS SUCCESS_COUNT,
  (SELECT COUNT(1) FROM RWSUSER.RFX_QUEUE_JOB q WHERE q.BATCH_STATUS_ID = bs.BATCH_STATUS_ID AND q.JOB_ESTATUS='F') AS FAIL_COUNT,
  (SELECT COUNT(1) FROM RWSUSER.RFX_QUEUE_JOB q WHERE q.BATCH_STATUS_ID = bs.BATCH_STATUS_ID AND q.JOB_ESTATUS NOT IN ('S','F')) AS OTHER_COUNT
FROM RWSUSER.BATCH_STATUS bs
WHERE bs.JOB_TYPE = '{jobType}'
  AND ({planTypeFilter})
  AND bs.TIME_SUBMITTED >= CURRENT TIMESTAMP - {days} DAYS
ORDER BY CASE
    WHEN bs.STATUS IN ('N','I') AND bs.TIME_SUBMITTED IS NOT NULL
      AND bs.TIME_SUBMITTED < CURRENT TIMESTAMP - {stalePendingDbMins} MINUTES THEN 0
    WHEN bs.STATUS IN ('N','I') THEN 1
    ELSE 2 END,
  bs.TIME_SUBMITTED DESC
FETCH FIRST {maxBatchDetailRows} ROWS ONLY;

-- queue jobs (running)
SELECT q.JOB_TYPE, COALESCE(EXEC_CRON, CHAR(QUEUE_SLEEP)) JOB_INTERVAL, PARAM_2, LAST_JOB_TIME, JOBS_PENDING
FROM RWSUSER.RFX_QUEUE q
LEFT JOIN RWSUSER.STD_QUEUE_JOB s ON s.QUEUE_ID = q.QUEUE_ID
WHERE q.QUEUE_STATUS = 'R'
ORDER BY JOBS_PENDING DESC, LAST_JOB_TIME;

-- payroll product features (sync)
SELECT FEATURE_ID, FEATURE_VALUE FROM RWSUSER.PRODUCT_FEATURE
WHERE FEATURE_ID IN ('RTA_INTEGRATION', 'PRIOR_PERIOD_EDIT', 'PRIOR_PERIOD_EDIT_LIMIT', 'PAYROLL_FILE_GEN');

-- WFM app URL (cached on Client.wfmAppUrl after first sync; re-query only when refreshAppUrl)
SELECT PARAM_VALUE FROM RWSUSER.RFX_CONFIG
WHERE PARAM_NAME = 'APPURL'
FETCH FIRST 1 ROW ONLY;

-- payroll frequency (TA_PAY_FILE_GEN_PROCESS)
SELECT FREQUENCY FROM RWSUSER.TA_PAY_FILE_GEN_PROCESS
WHERE FREQUENCY IS NOT NULL
FETCH FIRST 1 ROW ONLY;

-- payroll periods (current year)
SELECT DISTINCT VARCHAR_FORMAT(WEEK_START_DATE, 'yyyyMMdd') AS WEEK_START_DATE,
       VARCHAR_FORMAT(WEEK_END_DATE, 'yyyyMMdd') AS WEEK_END_DATE,
       VARCHAR_FORMAT(CURRENT DATE, 'yyyyMMdd') AS TODAY_YMD
FROM RWSUSER.RWS_CALENDAR
WHERE YEAR_NO = YEAR(CURRENT DATE)
   OR YEAR(WEEK_END_DATE) = YEAR(CURRENT DATE)
ORDER BY 1;

-- payroll generators (running)
SELECT JOB_TYPE FROM RWSUSER.RFX_QUEUE
WHERE QUEUE_STATUS = 'R';

-- payroll monitor: pay generator schedule + optional store group (PARAM_3 = DIST_LIST_ID)
-- Prefer either RTAPayrollFeedGeneratorJob (client-wide) OR RTANewPayFileGeneratorJob (store group)
-- OR RTA_PAYROLL_FILE_GEN; only QUEUE_STATUS = 'R' (ignore paused)
-- RWS_DIST_LIST.NAME is the store group display name
SELECT q.QUEUE_ID, q.JOB_TYPE, q.EXEC_CRON, q.QUEUE_SLEEP,
       q.LAST_JOB_TIME, q.JOBS_PENDING, q.QUEUE_STATUS,
       s.PARAM_3 AS DIST_LIST_ID,
       d.NAME AS DIST_LIST_NAME
FROM RWSUSER.RFX_QUEUE q
LEFT JOIN RWSUSER.STD_QUEUE_JOB s ON s.QUEUE_ID = q.QUEUE_ID
LEFT JOIN RWSUSER.RWS_DIST_LIST d
  ON TRIM(CAST(d.DIST_LIST_ID AS VARCHAR(32))) = TRIM(CAST(s.PARAM_3 AS VARCHAR(32)))
WHERE q.QUEUE_STATUS = 'R';
-- filter JOB_TYPE to RTAPayrollFeedGeneratorJob, RTANewPayFileGeneratorJob, RTA_PAYROLL_FILE_GEN
-- EXEC_CRON = pay release time after previous RWS_CALENDAR week completes
-- when PARAM_3 is null, unit counts are client-wide (all TA_UNIT_PAY_STATUS for the week)

-- payroll monitor: mapped units for store group (effective on pay week end)
SELECT UNIT_ID
FROM RWSUSER.RWS_DIST_STORE_MAP m
WHERE INTEGER(m.DIST_LIST_ID) = {distListId}
  AND INTEGER(m.EFF_DATESKEY) <= {weekEndDate}
  AND INTEGER(m.END_DATESKEY) >= {weekEndDate};

-- payroll monitor: previous-week unit progress scoped to store group
SELECT COUNT(*) AS TOTAL_CNT,
       SUM(CASE WHEN UPPER(TRIM(COALESCE(u.FILE_STATUS, ''))) = 'F' THEN 1 ELSE 0 END) AS F_CNT,
       SUM(CASE WHEN UPPER(TRIM(COALESCE(u.FILE_STATUS, ''))) = 'D' THEN 1 ELSE 0 END) AS D_CNT,
       SUM(CASE WHEN UPPER(TRIM(COALESCE(u.FILE_STATUS, ''))) = 'Q' THEN 1 ELSE 0 END) AS Q_CNT,
       SUM(CASE WHEN UPPER(TRIM(COALESCE(u.FILE_STATUS, ''))) NOT IN ('F', 'D', 'Q') THEN 1 ELSE 0 END) AS BLANK_CNT
FROM RWSUSER.TA_UNIT_PAY_STATUS u
WHERE INTEGER(u.WEEK_END_DATE) = {weekEndDate}
  AND EXISTS (
    SELECT 1 FROM RWSUSER.RWS_DIST_STORE_MAP m
    WHERE m.UNIT_ID = u.UNIT_ID
      AND INTEGER(m.DIST_LIST_ID) = {distListId}
      AND INTEGER(m.EFF_DATESKEY) <= {weekEndDate}
      AND INTEGER(m.END_DATESKEY) >= {weekEndDate}
  );

-- payroll unit file status for selected week (FILE_STATUS = F → generated)
-- WEEK_*_DATE are INTEGER yyyyMMdd; FILE_ID is BIGINT
-- generation time is TA_PAY_FILE.LAST_UPDATE_TIME / CREATION_TIME (yyyyMMddHHmmss)
SELECT u.UNIT_ID, u.WEEK_START_DATE, u.WEEK_END_DATE, u.FILE_STATUS, u.FILE_ID,
       f.CREATION_TIME, f.LAST_UPDATE_TIME, f.FILE_NAME
FROM RWSUSER.TA_UNIT_PAY_STATUS u
LEFT JOIN RWSUSER.TA_PAY_FILE f ON f.FILE_ID = u.FILE_ID
WHERE INTEGER(u.WEEK_END_DATE) = {weekEndDate}
ORDER BY u.UNIT_ID;

-- payroll adj outstanding (record counts only — no pay amounts; dates are INTEGER)
SELECT
  (SELECT COUNT(*) FROM RWSUSER.TA_COST_SEG_DIFF WHERE INTEGER(PAY_WEEK_END_DATE) = {weekEndDate}) AS COST_SEG_CNT,
  (SELECT COUNT(*) FROM RWSUSER.TA_DIFF_PAY_DETAIL WHERE INTEGER(PAY_WEEK_END_DATE) = {weekEndDate}) AS DIFF_PAY_CNT
FROM SYSIBM.SYSDUMMY1;

-- Heat map: distinct store counts for Manager (6) vs WIP (7)
-- Active shifts: EFF_DATE <= as-of AND END_DATE >= as-of (no RWS_CALENDAR join)
-- Row 1 = current week (as-of today); row 2 = previous week (as-of today - 7 days)
SELECT VARCHAR_FORMAT(COALESCE(MIN(g.EFF_DATE), CURRENT DATE), 'yyyyMMdd') AS WEEK_START_DATE,
       VARCHAR_FORMAT(COALESCE(MAX(g.END_DATE), CURRENT DATE), 'yyyyMMdd') AS WEEK_END_DATE,
       COUNT(DISTINCT CASE WHEN g.ITERATION_TYPE = 6 THEN g.UNIT_SKEY END) AS ITER6_STORES,
       COUNT(DISTINCT CASE WHEN g.ITERATION_TYPE = 7 THEN g.UNIT_SKEY END) AS ITER7_STORES
FROM RWSUSER.RWS_GEN_SHIFT g
WHERE g.EFF_DATE <= CURRENT DATE
  AND g.END_DATE >= CURRENT DATE
  AND g.ITERATION_TYPE IN (6, 7)
UNION ALL
SELECT VARCHAR_FORMAT(COALESCE(MIN(g.EFF_DATE), CURRENT DATE - 7 DAYS), 'yyyyMMdd') AS WEEK_START_DATE,
       VARCHAR_FORMAT(COALESCE(MAX(g.END_DATE), CURRENT DATE - 7 DAYS), 'yyyyMMdd') AS WEEK_END_DATE,
       COUNT(DISTINCT CASE WHEN g.ITERATION_TYPE = 6 THEN g.UNIT_SKEY END) AS ITER6_STORES,
       COUNT(DISTINCT CASE WHEN g.ITERATION_TYPE = 7 THEN g.UNIT_SKEY END) AS ITER7_STORES
FROM RWSUSER.RWS_GEN_SHIFT g
WHERE g.EFF_DATE <= CURRENT DATE - 7 DAYS
  AND g.END_DATE >= CURRENT DATE - 7 DAYS
  AND g.ITERATION_TYPE IN (6, 7);

-- unprocessed punches
SELECT COUNT(1) AS PUNCH_COUNT, MIN(LAST_UPDATE_TIME) AS LAST_UPDATE_TIME, CURRENT TIMESTAMP AS DB_CURRENT_TS
FROM RWSUSER.TA_UNPROC_PUNCH
WHERE PROCESS_FLAG = 'N'
  AND INTEGER(PUNCH_DATE) >= INTEGER(VARCHAR_FORMAT(CURRENT DATE - {punchLookbackDays} DAYS, 'yyyyMMdd'));
