-- Advanced Monitor: operational access beyond Monitor, below System Admin

INSERT OR IGNORE INTO "Profile" ("id", "name", "description", "isSystem", "createdAt", "updatedAt")
VALUES (
  'b7e3c914-2a5f-4d8e-9c1b-6f0a8d3e5c27',
  'Advanced Monitor',
  'Operational write access beyond Monitor (alerts, sync, maintenance, payroll) — no users/profiles/config admin',
  1,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO "Permission" ("profileId", "functionId", "canRead", "canWrite")
SELECT p.id, fn.functionId, 1, fn.canWrite
FROM "Profile" p
CROSS JOIN (
  SELECT 'ALERTS_VIEW' AS functionId, 0 AS canWrite UNION ALL
  SELECT 'ALERTS_RULES', 0 UNION ALL
  SELECT 'ALERTS_ACK', 1 UNION ALL
  SELECT 'ALERTS_SUPPRESS', 1 UNION ALL
  SELECT 'ALERTS_NOTIFY', 1 UNION ALL
  SELECT 'RECIPIENTS_MANAGE', 0 UNION ALL
  SELECT 'CLIENTS_VIEW', 0 UNION ALL
  SELECT 'CLIENTS_CREATE', 0 UNION ALL
  SELECT 'CLIENTS_EDIT', 0 UNION ALL
  SELECT 'CLIENTS_SYNC', 1 UNION ALL
  SELECT 'CLIENTS_DETECT_TZ', 1 UNION ALL
  SELECT 'JOBS_VIEW', 0 UNION ALL
  SELECT 'JOBS_CREATE', 0 UNION ALL
  SELECT 'JOBS_EDIT', 1 UNION ALL
  SELECT 'JOBS_TOGGLE', 1 UNION ALL
  SELECT 'JOBS_TRIGGER', 1 UNION ALL
  SELECT 'JOBS_LOG_TAIL', 1 UNION ALL
  SELECT 'DBMONITOR_VIEW', 0 UNION ALL
  SELECT 'DBJOBS_VIEW', 0 UNION ALL
  SELECT 'MONITOR_VIEW', 0 UNION ALL
  SELECT 'PAYROLL_VIEW', 0 UNION ALL
  SELECT 'PAYROLL_MONITOR_VIEW', 0 UNION ALL
  SELECT 'PAYROLL_SYNC', 1 UNION ALL
  SELECT 'UNPROC_PUNCH_VIEW', 0 UNION ALL
  SELECT 'UNPROC_PUNCH_REFRESH_ALL', 1 UNION ALL
  SELECT 'UNPROC_PUNCH_REFRESH_HIGH', 1 UNION ALL
  SELECT 'UNPROC_PUNCH_REFRESH_ROW', 1 UNION ALL
  SELECT 'MAINTENANCE_VIEW', 0 UNION ALL
  SELECT 'MAINTENANCE_MANAGE', 1 UNION ALL
  SELECT 'OUTAGE_VIEW', 0 UNION ALL
  SELECT 'FILE_MONITOR_VIEW', 0 UNION ALL
  SELECT 'USERS_VIEW', 0 UNION ALL
  SELECT 'PROFILES_VIEW', 0 UNION ALL
  SELECT 'DATA_PURGE_VIEW', 0 UNION ALL
  SELECT 'DATA_PURGE_RUN', 0
) fn
INNER JOIN "AppFunction" af ON af.id = fn.functionId
WHERE p."isSystem" = 1 AND p.name = 'Advanced Monitor';
